vich_uploader:
    db_driver: orm

    mappings:
        produits:
           uri_prefix: /images/produits
           upload_destination: '%kernel.project_dir%/public/images/produits'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
